apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab-deployment
  template:
    metadata:
      labels:
        app: gitlab-deployment
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: gitlab-storage-data
          persistentVolumeClaim:
            claimName: gitlab-pvc-data
        - name: gitlab-storage-log
          persistentVolumeClaim:
            claimName: gitlab-pvc-log
        - name: gitlab-storage-config
          persistentVolumeClaim:
            claimName: gitlab-pvc-config
      containers:
      - name: gitlab-deployment
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        volumeMounts:
        - name: gitlab-storage-data
          mountPath: /var/opt/gitlab
        - name: gitlab-storage-log
          mountPath: /var/log/gitlab
        - name: gitlab-storage-config
          mountPath: /etc/gitlab
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "3"
