apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-job
  namespace: rocket-chat
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo 8.0
        command: ["mongosh"]
        args:
        - "--host"
        - "mongo-state-0.rocket-chat-mongo.rocket-chat.svc.cluster.local"
        - "--eval"
        - "rs.initiate({_id: 'rs0', members: [{ _id: 0, host: 'mongo-state-0.rocket-chat-mongo.rocket-chat.svc.cluster.local:27017' },{ _id: 1, host : "mongo-state-1.mongo-service.rocket-chat.svc.cluster.local:27017" },{ _id: 2, host : "mongo-state-2.mongo-service.rocket-chat.svc.cluster.local:27017" }]})"